import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>Weather</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, user-scalable=no" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <body className='bgs'>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
